name: Release

on:
  release:
    branches:
      - 'master'
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install nodejs
        uses: actions/setup-node@v1
        with:
          node-version: '18.0.0'

      - name: Make envfile
        uses: SpicyPizza/create-envfile@v1
        with:
          envkey_GATSBY_GOOGLE_ANALYTICS_TRACKING_ID: ${{ secrets.GATSBY_GOOGLE_ANALYTICS_TRACKING_ID }}
          file_name: .env

      - name: Install dependencies
        run: npm install --force

      - name: Build
        run: npm run build

      - name: Copy file via ssh key
        uses: appleboy/scp-action@master
        with:
          HOST: ${{ secrets.PRODUCTION_HOST }}
          USERNAME: ${{ secrets.USERNAME }}
          PORT: ${{ secrets.PORT }}
          KEY: ${{ secrets.PRODUCTION_KEY }}
          source: './public'
          target: '/home/manjiltamang'

      - name: Executing remote command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PRODUCTION_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.PRODUCTION_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/manjiltamang.com/html
            rm -rf ./*
            mv /home/manjiltamang/public/* ./
